version: '2.3'

services:

    # APP SERVICES

    php:
        build: docker/php
        volumes:
            - "./:/project"
            - "./docker/php/conf/php-fpm.conf:/etc/php-fpm.conf"
            - "./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/100-php.ini"
        depends_on:
            - mysql
            - maildev

    nginx:
        build: docker/nginx
        volumes:
            - "./:/project"
            - "./docker/nginx/conf/project.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php

#    httpd:
#        build: docker/httpd
#        volumes:
#            - "./:/project"
#            - "./docker/httpd/conf/project.conf:/usr/local/apache2/conf/extra/100-project-vhost.conf"
#        depends_on:
#            - php

    mysql:
        build: docker/mysql
        volumes:
            - "./docker/mysql/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf"

    node:
        build: docker/node
        volumes:
            - "./:/project"

    # DEVELOPMENT SERVICES

    maildev:
        image: djfarrelly/maildev

#    blackfire:
#        image: blackfire/blackfire

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin:4.7
#        depends_on:
#            - mysql
#        links:
#            - "mysql:db"
