version: '3'

services:

    # APP SERVICES

    php:
        build: docker/php
#        uncomment the following lines to use php 7.1
#        build:
#            context: docker/php
#            dockerfile: Dockerfile-7.1
        volumes:
            - "./:/project"
        depends_on:
            - mysql
            - maildev
        env_file:
            - "docker/.env"

    nginx:
        build: docker/nginx
#        uncomment the following lines to use nginx with pagespeed module
#        build:
#            context: docker/nginx
#            dockerfile: Dockerfile-pagespeed
        volumes:
            - "./:/project"
        depends_on:
            - php

    mysql:
        build: docker/mysql
        env_file:
            - "docker/.env"

    node:
        build: docker/node
        volumes:
            - "./:/project"

    # ALTERNATIVES SERVICES

#    httpd:
#        build: docker/httpd
#        volumes:
#            - "./:/project"
#        depends_on:
#            - php

    # DEVELOPMENT TOOLS SERVICES

    maildev:
        image: djfarrelly/maildev

#    blackfire:
#        image: blackfire/blackfire
#        env_file:
#            - "docker/.env"

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin:4.7
#        depends_on:
#            - mysql
#        links:
#            - "mysql:db"
#        env_file:
#            - "docker/.env"
