version: '3'

services:

    # APP SERVICES

    php:
        build: docker/php
        volumes:
            - "./:/project"
        depends_on:
            - mysql
            - maildev

    nginx:
        build: docker/nginx
        volumes:
            - "./:/project"
        depends_on:
            - php

    node:
        build: docker/node
        volumes:
            - "./:/project"

    mysql:
        build: docker/mysql

    # ALTERNATIVES SERVICES

#    httpd:
#        build: docker/httpd
#        volumes:
#            - "./:/project"
#        depends_on:
#            - php

    # DEVELOPMENT TOOLS SERVICES

    maildev:
        image: djfarrelly/maildev

#    blackfire:
#        image: blackfire/blackfire

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin:4.7
#        depends_on:
#            - mysql
#        links:
#            - "mysql:db"
